# Generated by Django 5.2.6 on 2025-09-07 18:47

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("blogs", "0002_alter_catergory_options_blog"),
    ]

    operations = [
        migrations.RenameModel(
            old_name="Catergory",
            new_name="Category",
        ),
        migrations.RenameField(
            model_name="blog",
            old_name="catergory",
            new_name="category",
        ),
    ]
